name: Deploy/Teardown Images Bucket

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: DeployOrTearDown
        options:
          - Deploy
          - TearDown

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./images
        

    steps:
      - uses: actions/checkout@v4
    
      - uses: hashicorp/setup-terraform@v2

      - run: terraform init

      - run: terraform validate

      - run: terraform plan

      - name: Deploy or TearDown
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Deploy' ]; then  
            terraform apply -auto-approve
          elif [ ${{ github.event.inputs.deployment }} == 'TearDown' ]; then  
            terraform destroy -auto-approve
          fi
        shell: bash

      - name: Push S3 images bucket url to organization variables
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Deploy' ]; then  
            cat s3_bucket_images_url.dat
            source s3_bucket_images_url.dat
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/S3_BUCKET_IMAGES_URL -d '{"name":"S3_BUCKET_IMAGES_URL","value":"'$S3_BUCKET_IMAGES_URL'","visibility":"all"}'
          elif [ ${{ github.event.inputs.deployment }} == 'TearDown' ]; then
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/S3_BUCKET_IMAGES_URL -d '{"name":"S3_BUCKET_IMAGES_URL","value":"DESTROYED","visibility":"all"}'
          fi

      - name: Push API Gateway upload images bucket url to organization variables
        run: |
          if [ ${{ github.event.inputs.deployment }} == 'Deploy' ]; then  
            cat api_gateway_upload_images_url.dat
            source api_gateway_upload_images_url.dat
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/API_GATEWAY_UPLOAD_IMAGES_URL -d '{"name":"API_GATEWAY_UPLOAD_IMAGES_URL","value":"'$API_GATEWAY_UPLOAD_IMAGES_URL'","visibility":"all"}'
          elif [ ${{ github.event.inputs.deployment }} == 'TearDown' ]; then
            curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/API_GATEWAY_UPLOAD_IMAGES_URL -d '{"name":"API_GATEWAY_UPLOAD_IMAGES_URL","value":"DESTROYED","visibility":"all"}'
          fi